# Generated by Django 5.2.7 on 2026-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_appuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
