# Generated by Django 5.2.7 on 2026-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_appuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
